amazon:
  s3:
    accessKey: componentTests
spring:
  security:
    user:
      name: carterkent
      password: carterkent
      roles: SUPERUSER
  data:
    rest:
      default-page-size: 2
  main:
    allow-bean-definition-overriding: true